### ISSUE TITLE
[!]   Load RuleFile list Error: undefined method `size' for nil:NilClass 

### ISSUE THREAD

**Issue by line2222** [anbai-inc/AttackFilter#1]
[!]   Load RuleFile list Error: undefined method `size' for nil:NilClass 
>, :backtrace=>["/root/elk/logstash-6.2.0/vendor/local_gems/e6a2c091/logstash-filter-attackfilter-1.0.6/lib/logstash/filters/attackfilter.rb:88:in `register'", "/root/elk/logstash-6.2.0/logstash-core/lib/logstash/pipeline.rb:341:in `register_plugin'", "/root/elk/logstash-6.2.0/logstash-core/lib/logstash/pipeline.rb:352:in `block in register_plugins'", "org/jruby/RubyArray.java:1734:in `each'", "/root/elk/logstash-6.2.0/logstash-core/lib/logstash/pipeline.rb:352:in `register_plugins'", "/root/elk/logstash-6.2.0/logstash-core/lib/logstash/pipeline.rb:736:in `maybe_setup_out_plugins'", "/root/elk/logstash-6.2.0/logstash-core/lib/logstash/pipeline.rb:362:in `start_workers'", "/root/elk/logstash-6.2.0/logstash-core/lib/logstash/pipeline.rb:289:in `run'", "/root/elk/logstash-6.2.0/logstash-core/lib/logstash/pipeline.rb:249:in `block in start'"], :thread=>"#<Thread:0x3bcda05 run>"}
[2018-02-11T16:40:46,174][ERROR][logstash.agent           ] Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: LogStash::PipelineAction::Create/pipeline_id:main, action_result: false", :backtrace=>nil}

**Comment by anbai-inc** [comment]
你当前的es和logstash版本过高导致的不兼容，需要调整下代码
