### ISSUE TITLE
插件的文档

### ISSUE THREAD

**Issue by Linoonphan** [anbai-inc/AttackFilter#3]
插件文档网站不能打开，插件文档哪里有呢

**Comment by ver007** [comment]
稍后将重开一个文档

**Comment by Linoonphan** [comment]
> 文档已经转到这里了 http://ver007.org/?p=714

谢谢

**Comment by jkgao801** [comment]
http://ver007.org/?p=714   这个链接 打开是 nginx 的网站。能否提供一下插件文档，谢谢
